stages:
  # - Static Analysis
  # - Test
  - Release
  # - Deploy

# eslint:
#   stage: Static Analysis
#   image: node:20-slim
#   before_script:
#     - node -v
#     - npm -v
#     - npm install
#     - npm install --save-dev eslint
#   script:
#     - npx eslint src --format json --output-file eslint_report.json || true
#     - npx eslint src | tee eslint_report.txt
#   artifacts:
#     when: always
#     paths:
#       - eslint_report.txt
#       - eslint_report.json
#   allow_failure: true

# integration-tests:
#   stage: Test
#   image: docker:28.3.2
#   services:
#     - docker:28.3.2-dind
#   before_script:
#     - docker info
#   script:
#     - docker compose -f ci/compose.test.yaml up --exit-code-from insurance-pytest

release-image:
  stage: Release
  image: docker:28.3.2
  services:
    - docker:28.3.2-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest" -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH" --all-tags

# deploy-ecs:
#   stage: Deploy
#   image: 'registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest'
#   environment:
#     name: production-ecs
#   rules:
#     - if: '$CI_COMMIT_REF_NAME == "main"'
#   script:
#     - ecs update-task-definition