apiVersion: v1
kind: Service
metadata:
  name: events-stream
spec:
  type: NodePort
  selector:
    app: events-stream
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-stream
  labels:
    app: events-stream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-stream
  template:
    metadata:
      labels:
        app: events-stream
    spec:
      containers:
        - name: events-stream
          image: registry.gitlab.com/cs302-2025/g2-team5/services/events-stream/main:4037a105a77eb546308ff4bf9f2863b7aa790e89
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - secretRef:
                name: env-vars-secret
            - configMapRef:
                name: env-vars-configmap
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: gitlab-registry-access-g2t5
