apiVersion: v1
kind: Service
metadata:
  name: triage
spec:
  type: NodePort
  selector:
    app: triage
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage
  labels:
    app: triage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: triage
  template:
    metadata:
      labels:
        app: triage
    spec:
      containers:
        - name: triage
          image: registry.gitlab.com/cs302-2025/g2-team5/services/triage/main:1f518f02052b03faae2f0fb69b41f166506f9268
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: env-vars-secret
            - configMapRef:
                name: env-vars-configmap
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: gitlab-registry-access-g2t5
